const data = {
	trending: [
		{
			id: 1,
			keyword: 'George Russell',
			desc: 'George Russell continues his streak of finishing in the top 5...',
			community: 'r/formula1',
			logo: './images/community_icons/community_icon_1.jpg',
			image: './images/trending/trending_1.jpg',
		},
		{
			id: 2,
			keyword: 'Donald Trump',
			desc: "Formal White House counsel says Trump is 'likely' to be...",
			community: 'r/politics',
			logo: './images/community_icons/community_icon_2.png',
			image: './images/trending/trending_2.jpg',
		},
		{
			id: 3,
			keyword: 'Inflation',
			desc: 'Inflation rose 8.6% in May, highest since 1981',
			community: 'r/news',
			logo: './images/community_icons/community_icon_2.png',
			image: './images/trending/trending_3.jpg',
		},
		{
			id: 4,
			keyword: 'Uvalde Police Statement',
			desc: "Uvalde's school district police chief said he intetionally left...",
			community: 'r/nottheunion',
			logo: './images/community_icons/community_icon_3.png',
			image: './images/trending/trending_4.jpg',
		},
	],
	posts: [
		{
			id: 1,
			likes: '12.4k',
			community_icon: './images/community_icons/community_icon_3.png',
			community: 'r/facepalm',
			posted_by: 'u/TheRookieGetsCookie',
			posted_time: '7',
			title: "He isn't very good at hints.",
			category_icon: './images/category_icons/misc.png',
			category: 'misc',
			text: '',
			image: './images/posts/post_1.jpg',
			comments: '452',
		},
		{
			id: 2,
			likes: '6.1k',
			community_icon: './images/community_icons/community_icon_2.png',
			community: 'r/pokemon',
			posted_by: 'u/snailscale77',
			posted_time: '23',
			title: 'What unpopular Pokémon opinion would make most fans angry?',
			category_icon: '',
			category: 'discussion',
			text: 'I’ll start. I love exp share. Gen 6 probably has the best designed Pokémon on average. Gen 7 had my favorite cast of characters. I absolutely love the tepig line. Fennekin is my favorite first form starter. The Gen 2 starters final evolutions are bland and overrated. I can’t stand blaziken. Misty is the worst companion Ash has had, and I actually like the first Diamond and Pearl Pokémon opening (English).',
			image: '',
			comments: '4.4k',
		},
		{
			id: 3,
			likes: '33.8k',
			community_icon: './images/community_icons/community_icon_4.png',
			community: 'r/mildlyinteresting',
			posted_by: 'u/DrAbenauer',
			posted_time: '8',
			title:
				"My father's collection of paintbrushes he has forgotten in dried resin and varnish.",
			category_icon: '',
			category: '',
			text: '',
			image: './images/posts/post_2.png',
			comments: '292',
		},
		{
			id: 4,
			likes: '35.1k',
			community_icon: './images/community_icons/community_icon_5.png',
			community: 'r/MapPorn',
			posted_by: 'u/theworldmaps',
			posted_time: '23',
			title: 'The most popular sport in every country in the world',
			category_icon: '',
			category: '',
			text: '',
			image: './images/posts/post_3.jpg',
			comments: '3.4k',
		},
	],
}

export default data
